# 站点基础信息
title: "陈奕杉 | 机器人/自动驾驶算法工程师"
name: "陈奕杉"
bio: "自动驾驶数据闭环背景 → 具身智能感知与数据闭环"
description: "3年机器人工程科研经验，4年自动驾驶算法工作经验，精通数据闭环、环境重建"

# 联系方式
email: "11930357@mail.sustech.edu.cn"
github_username: "TonyChen-0357"
linkedin: "--"

# 导航栏
navigation:
  - title: "关于我"
    url: "/"
  - title: "项目"
    url: "/projects/"
  - title: "简历"
    url: "/cv/"
  - title: "博客"
    url: "/posts/"
